# Generated by Django 2.2.4 on 2019-08-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, max_length=254, null=True, upload_to='photos/'),
        ),
    ]
