# Generated by Django 2.2.4 on 2019-08-23 23:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageApi', '0002_auto_20190824_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='BMI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi', models.IntegerField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.ImageField(default=1, upload_to='photo/'),
            preserve_default=False,
        ),
    ]
