# Generated by Django 2.2.4 on 2019-08-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('weightcurrent', models.IntegerField()),
                ('bmicurrent', models.IntegerField()),
            ],
        ),
    ]
