# Generated by Django 2.2.4 on 2019-08-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelmaker', '0002_auto_20190823_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bmicurrent',
        ),
    ]
