# Generated by Django 2.2.4 on 2019-08-24 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi', models.IntegerField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='ylinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ylinks1', models.CharField(max_length=200)),
                ('ylinks2', models.CharField(max_length=200)),
                ('ylinks3', models.CharField(max_length=200)),
                ('ylinks4', models.CharField(max_length=200)),
                ('ylinks5', models.CharField(max_length=200)),
                ('ylinks6', models.CharField(max_length=200)),
                ('ylinks7', models.CharField(max_length=200)),
                ('ylinks8', models.CharField(max_length=200)),
                ('ylinks9', models.CharField(max_length=200)),
                ('ylinks10', models.CharField(max_length=200)),
            ],
        ),
    ]
